# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

handle_na <- function(x, y, method) {
    .Call(`_cor_package_handle_na`, x, y, method)
}

cor_new_rcpp <- function(x, y, method = "pearson", na_handle = "complete") {
    .Call(`_cor_package_cor_new_rcpp`, x, y, method, na_handle)
}

